project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("servicios/", include("servicios.urls")),
    path("eventos/", include("eventos.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from. import views

app_name = "core"

urlpatterns = [
    path('', views.home, name='home'),
    path("about/", views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    
]

urlpatterns += staticfiles_urlpatterns()

project/eventos/urls.py
from django.urls import path
from . import views

app_name = "eventos"

urlpatterns = [
    path('', views.home, name='home'),
    path("eventos/list/", views.EventosList.as_view(), name="eventos_list"),
    path("eventos/form/", views.EventoCreate.as_view(), name="eventos_form"),
    path("eventos/delete/<int:pk>", views.EventoDelete.as_view(), name="eventos_delete"),
    path("eventos/update/<int:pk>", views.EventoUpdate.as_view(), name="eventos_update"),
    # path("eventos/update/<int:pk>", views.eventos_update, name="eventos_update"),
    path("eventos/detail/<int:pk>", views.EventoDetail.as_view(), name="eventos_detail"),
]

project/eventos/models.py
from django.db import models
from cliente.models import Cliente
from servicios.models import Servicios
# Create your models here.

class Eventos(models.Model):
    cliente = models.ForeignKey(
        Cliente, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Cliente"
        )
    servicio = models.ForeignKey(
        Servicios, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Servicio a realizar"
        )
    fecha_evento = models.DateField(verbose_name= "Fecha evento", blank=False)

    def __str__(self):
        return f"Fecha evento: {self.fecha_evento} Servicio: {self.servicio} Cliente: {self.cliente}"
    
    class Meta:
        verbose_name_plural = "Eventos"

project/eventos/forms.py
from django import forms
from . import models

class EventosForm(forms.ModelForm):
    class Meta:
        model = models.Eventos
        fields = "__all__"       

project/eventos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from . import models, forms

def home(request):
    # query = models.Eventos.objects.all()
    # context = {"eventos" : query}
    # return render(request, "eventos/index.html", context)
    return render(request, "eventos/index.html")

# Listar eventos y filtar por busqueda de fecha 
class EventosList(ListView):
    model = models.Eventos

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Eventos.objects.filter(fecha_evento=consulta)
        else:
            object_list = models.Eventos.objects.all()
        return object_list

# Crear nuevo evento
class EventoCreate(CreateView):
    model = models.Eventos
    form_class = forms.EventosForm
    success_url = reverse_lazy("eventos:home")


# UPDATE
# def eventos_update(request, pk: int):
#     query = models.Eventos.objects.get(id=pk)
#     if request.method == "POST":
#         form = forms.EventosForm(request.POST, instance=query)
#         if form.is_valid:
#             form.save()
#             return redirect("eventos:eventos_list")
#     else:  # request.method == "GET"
#         form = forms.EventosForm(instance=query)
#     return render(request, "eventos/eventos_update.html", context={"form": form})

class EventoUpdate(UpdateView):
    model = models.Eventos
    form_class = forms.EventosForm
    template_name = "eventos/eventos_update.html"
    success_url = reverse_lazy("eventos:eventos_list")


class EventoDetail(DetailView):
    model = models.Eventos


# class EventoDelete(LoginRequiredMixin, DeleteView):
class EventoDelete(DeleteView):
    model = models.Eventos
    success_url = reverse_lazy("eventos:eventos_list")

project/eventos/templates/eventos/eventos_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Eliminar agenda de evento
{% endblock titulo %}

{% block contenido %}
<div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px; text-align: center;">    
    <p class="fs-5 fst-italic">Esta a punto de eliminar este evento de la agenda. ¿Desea continuar?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a class = "btn btn-primary"href="{% url 'eventos:eventos_list' %}">Volver al listado</a>
    </div>
</div>
{% endblock contenido %}

project/eventos/templates/eventos/eventos_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
    Detalle evento
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-12">
                            Fecha evento: {{ object.fecha_evento }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            Servicio: {{ object.servicio.nombre }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            Cliente: {{ object.cliente }}
                        </div>
                    </div>
                    <!-- Agrega más campos si es necesario -->
                </li>
            </ul>
            <div class="text-center mt-4">
                <a href="{% url 'eventos:eventos_list' %}" class="btn btn-primary btn-lg">Volver</a>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

project/eventos/templates/eventos/eventos_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Agendar evento
{% endblock titulo %}

{% block contenido %}
<form method="post" style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
    {% csrf_token %}
    <table style="margin: 0 auto;">
        {{ form.as_table }}
    </table>
    <div style="text-align: center;">
    <button type="submit" style="margin-top: 10px;" class="btn btn-primary">Guardar</button>
    </div>
</form>
{% endblock contenido %}

project/eventos/templates/eventos/eventos_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Listado de eventos
{% endblock titulo %}
{% block contenido %}
<div class="container">
    <div class="row mb-4">
        <div class="col-lg-6">
            <form action="{% url 'eventos:eventos_list' %}" method="get" class="d-flex">
                <input type="date" name="consulta" class="form-control me-2">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-group">
                {% for evento in object_list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>{{ evento.fecha_evento }}</span>
                    <div>
                        <a class="btn btn-outline-primary btn-sm me-1" href="{% url 'eventos:eventos_detail' evento.id %}">Detalle</a>
                        <a class="btn btn-outline-secondary  btn-sm me-1" href="{% url 'eventos:eventos_update' evento.id %}">Cambiar</a>
                        <a class="btn btn-outline-danger btn-sm" href="{% url 'eventos:eventos_delete' evento.id %}">Borrar</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-lg-12">
            <div class="fs-3">
                <a href="{% url 'eventos:home' %}" class="btn btn-secondary">Volver</a>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}

project/eventos/templates/eventos/eventos_update.html
{% extends 'core/base.html' %}

{% block titulo %}
    Modificar agenda
{% endblock titulo %}

{% block contenido %}
<div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <div style="text-align: center;">
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
    <div class="fs-3 pb-4">
        <a style="float: right;" class="btn btn-primary" href="{% url 'eventos:eventos_list' %}">Volver</a>
    </div>
</div>
{% endblock contenido %}

project/eventos/templates/eventos/index.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="text-center mb-4">Eventos</h1>
{% endblock titulo %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="row mb-3">
                <div class="col-md-6 text-center">
                    <a href="{% url 'eventos:eventos_form' %}" class="btn btn-primary btn-lg btn-block">Agendar nuevo evento</a>
                </div>
                <div class="col-md-6 text-center">
                    <a href="{% url 'eventos:eventos_list' %}" class="btn btn-secondary btn-lg btn-block">Ver agenda</a>  
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 text-center">
                    
                </div>
                <div class="col-md-6 text-center">
                
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}