project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("servicios/", include("servicios.urls")),
    path("eventos/", include("eventos.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from. import views

app_name = "core"

urlpatterns = [
    path('', views.home, name='home'),
    path("about/", views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    
]

urlpatterns += staticfiles_urlpatterns()

project/servicios/urls.py
from django.urls import path 
from . import views
app_name = "servicios"

urlpatterns = [
    path('', views.home, name='home'),
    path('servicios/create', views.servicios_create, name='servicios_create'),    
]

project/servicios/models.py
from django.db import models

# Create your models here.

class Servicios(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.CharField(max_length=500, null = True, blank = True)
    avatar = models.ImageField(upload_to="avatares", null = True, blank = True)
    
    def __str__(self) -> str:
        return f"Servicio: {self.nombre} Descripción: {self.descripcion}"
    
    class Meta:
        verbose_name_plural = "Servicios"

project/servicios/forms.py
from django import forms
from . import models

class ServiciosForm(forms.ModelForm):
    class Meta:
        model = models.Servicios
        fields = "__all__"
        # widgets = {
        #     "nombre": forms.TextInput(attrs={"class": "form-control"}),
        # #    "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        # }

project/servicios/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from . import models, forms

# Create your views here.

def home(request):
    query = models.Servicios.objects.all()
    context = {"servicios" : query}
    return render(request, "servicios/index.html", context)

def servicios_create(request):
    if request.method == "POST":
        form = forms.ServiciosForm(request.POST, request.FILES)
        if form.is_valid:
            form.save()
            return redirect("servicios:home")
    else:  # request.method == "GET"
        form = forms.ServiciosForm()
    return render(request, "servicios/servicios_create.html", context={"form": form})

project/servicios/templates/servicios/index.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1 class="mb-4">Servicios</h1>
{% endblock titulo %}

{% block contenido %}
    {% if user.is_authenticated %}
        <div class="text-center mb-4" style="position: relative; z-index: 10;">
            <a href="{% url 'servicios:servicios_create' %}" class="btn btn-primary">Crear nuevo servicio</a>
        </div>
    {% endif %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for servicio in servicios %}
            <div class="col mb-4">
                <div class="card shadow-sm h-100 text-center">
                    <div class="card-body">
                        <h2 class="card-title mb-3">{{ servicio.nombre }}</h2>
                        <div class="d-flex justify-content-center mb-3">
                            {% if servicio.avatar %}
                                <img src="{{ servicio.avatar.url }}" class="img-fluid rounded">
                            {% else %}
                                <p class="mt-3">No hay imagen disponible para este servicio.</p>
                            {% endif %}
                        </div>
                        {% if servicio.descripcion %}
                            <p class="card-text">Descripción: {{ servicio.descripcion }}</p>
                        {% endif %} 
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>    
</div>
{% endblock contenido %}

project/servicios/templates/servicios/servicios_create.html
{% extends 'core/base.html' %}

{% block titulo %}
<div align="center">
    <h1 class="fs-7">Ingresar nuevo servicio</h1>
</div>
{% endblock titulo %}

{% block contenido %}
{% if user.is_authenticated %}
<div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
<div align="center">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-2 pb-4">
        <a class = "btn btn-primary"href="{% url 'servicios:home' %}">Volver a Servicios</a>
    </div>
</div>
</div>
{% else %}
<div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
    <h1>Debe estar logeado para tener acceso a esta pagina</h1>
</div>
{% endif %}

{% endblock contenido %}