project/cliente/urls.py
from django.urls import path 
from. import views

app_name = "cliente"

urlpatterns = [
    path('', views.home, name='home'),
    
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cliente/", include("cliente.urls")),
    path("servicios/", include("servicios.urls")),
    path("eventos/", include("eventos.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from. import views

app_name = "core"

urlpatterns = [
    path('', views.home, name='home'),
    path("about/", views.about, name="about"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("register/", views.register, name="register"),
    
]

urlpatterns += staticfiles_urlpatterns()

project/eventos/urls.py
from django.urls import path
from . import views

app_name = "eventos"

urlpatterns = [
    path('', views.home, name='home'),
    path("eventos/list/", views.EventosList.as_view(), name="eventos_list"),
    path("eventos/form/", views.EventoCreate.as_view(), name="eventos_form"),
    path("eventos/delete/<int:pk>", views.EventoDelete.as_view(), name="eventos_delete"),
    path("eventos/update/<int:pk>", views.EventoUpdate.as_view(), name="eventos_update"),
    # path("eventos/update/<int:pk>", views.eventos_update, name="eventos_update"),
    path("eventos/detail/<int:pk>", views.EventoDetail.as_view(), name="eventos_detail"),
]

project/servicios/urls.py
from django.urls import path 
from . import views
app_name = "servicios"

urlpatterns = [
    path('', views.home, name='home'),
    path('servicios/create', views.servicios_create, name='servicios_create'),    
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
        }

project/core/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "core/index.html")

def about(request):
    return render(request, "core/about.html")

class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"


#@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "core/index.html", {"mensaje": "Usuario creado"})
    else:
        form = CustomUserCreationForm()
    return render(request, "core/register.html", {"form": form})

project/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block titulo %}
<div style = "text-align: center;">
    <h1>Sobre mi.</h1>
</div>
{% endblock titulo %}

{% block contenido %}
    <div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
        <p>Mi nombre es Marcos Paz. Aunque tengo experiencia en programación en C# y bases de datos SQL, ha pasado algún tiempo desde que trabajé en esos campos. Decidí cursar Python para actualizarme y adaptarme a las tecnologías más actuales, con la esperanza de encontrar oportunidades laborales que me permitan seguir mi pasión.</p>

        <p>Actualmente estoy trabajando en este proyecto final, que está en proceso de desarrollo. La idea principal es crear una plataforma donde los clientes puedan encontrar y contratar servicios gastronómicos para sus eventos o reuniones. Además de ofrecer información detallada sobre los servicios, también queremos facilitar el contacto a través de WhatsApp.</p>

        <p>Esta página no solo será beneficiosa para los clientes, sino también para los proveedores de servicios gastronómicos. Les permitirá gestionar una agenda con los futuros servicios a ofrecer, así como mantener un registro de los clientes y sus detalles de contacto. También podrán compartir fotos y detalles de sus servicios.</p>

        <p>Nuestro objetivo a largo plazo es mejorar continuamente la funcionalidad de la página para hacerla más útil y eficiente para todos los usuarios.</p>
    </div>
    <div style = "text-align: right;">
    <a class= "btn btn-primary "href="{% url 'core:home' %}">Ir a inicio</a>
    </div>
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
                Legends fiestas y eventos
            {% endblock title %}
        </title>
        <!-- Favicon-->
        <link rel="icon"
              type="image/x-icon"
              href="{% static 'core/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
        <style>
            body {
                background-image: url("{% static 'core/img/bg.jpg' %}");
                background-size: cover;
                background-position: center;
            }
        </style>
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Servicios gourmet</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active"
                               aria-current="page"
                               href="{% url 'core:home' %}">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'servicios:home' %}">Servcios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:about' %}">About</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'cliente:home' %}">Cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'eventos:home' %}">Eventos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-bg-info">{{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <form action="{% url 'core:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-dark {{ fontsize }} ">Logout</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'core:login' %}">Login</a>
                            </li>
                            <li class="nav-item"> 
                                <a class="nav-link" href="{% url 'core:register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <div style="color: white;">
                {% block titulo %}
                {% endblock titulo %}
            </div>
            {% block contenido %}
            {% endblock contenido %}
        </div>
        <!-- Footer-->
        <footer class="py-1 bg-dark fixed-bottom">
            <div class="container px-4 px-lg-5">
                <p class="m-0 text-center text-white">Legend´s  &copy;</p>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    

{% endblock titulo %}

{% block contenido %}
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/img/intro.jpg' %}" alt="..." /></div>
        <div class="col-lg-5">
            <div style="color: white;">
            <h1 class="font-weight-light">Sobre nosotros...</h1>
            <p>Nuestro equipo está dedicado a crear momentos inolvidables a través de la comida, comprometiéndonos a utilizar ingredientes frescos y de la más alta calidad. Nos esforzamos por cumplir con las expectativas de nuestros clientes, superando incluso las más exigentes, mientras mantenemos un compromiso constante con la sostenibilidad y la responsabilidad social.

                Puede confiar en que su evento, reunión o celebración estará en manos de profesionales comprometidos que se esfuerzan por ofrecer un servicio excepcional en cada ocasión.
                
                Esperamos tener la oportunidad de colaborar con usted y crear momentos memorables.</p>
        </div>
            <a class="btn btn-primary" href="https://wa.me/542619999999" target="_blank">WhatsApp</a>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">Aqui te dejamos algunos de nuestos servicios</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Tablas gourmet</h2>
                    <p class="card-text">Disfruta de una experiencia gourmet con nuestras tablas de fiambres y panes. Saborea una selección exquisita de embutidos artesanales, quesos premium y panes frescos, perfectos para cualquier ocasión. Desde reuniones íntimas hasta eventos especiales, nuestras tablas añaden un toque de sofisticación a tus celebraciones. Deléitate con la frescura y el sabor de nuestros productos</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Brochetas con papas noisets</h2>
                    <p class="card-text">Descubre la delicia de nuestras brochetas y papas noisettes. Desde brochetas de carne marinada hasta opciones vegetarianas, cada bocado es una explosión de sabor. Acompañadas de crujientes papas noisettes. Una combinación irresistible que satisfará a todos los paladares."</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-5">
            <div class="card h-100">
                <div class="card-body">
                    <h2 class="card-title">Show de pizzas</h2>
                    <p class="card-text">Deléitate con nuestras pizzas artesanales, preparadas con ingredientes frescos y masa crujiente. Desde clásicas margaritas hasta combinaciones gourmet, cada pizza es una experiencia culinaria única. Perfectas para reuniones, fiestas o eventos, nuestras pizzas satisfacen todos los antojos con su sabor auténtico y delicioso.</p>
                </div>                
            </div>
        </div>
    </div>
{% endblock contenido %}

project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block titulo %}
    Login
{% endblock titulo %}

{% block contenido %}

    <div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
        <h1 style="margin-top: 0;">Login</h1>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="next" value="{% url 'core:home' %}">

            <button type="submit" style="margin-top: 10px;" class="btn btn-primary">Iniciar Sesión</button>
            <a href="{% url 'core:home' %}" style="margin-top: 10px;" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>

{% endblock contenido %}

project/core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block titulo %}
    Logout
{% endblock titulo %}
{% block contenido %}
    <div style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px; text-align: center;">
        <h1 style="margin-top: 0;" class="display-4">Has cerrado sesión</h1>
    </div>
{% endblock contenido %}

project/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block titulo %}
{% endblock titulo %}

{% block contenido %}

<div class="container" style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 50px;">
    <h1 class="mt-4">Registro de usuario</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Registrar nuevo usuario</button>
    </form>
</div>


{% endblock contenido %}